/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "include/secp256k1.h"
#include "include/blowfish.h"
/* Header for class org_bitcoin_Secp256k1Context */

#ifndef _Included_org_bitcoin_NativeBlowfish
#define _Included_org_bitcoin_NativeBlowfish
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_bitcoin_NativeBlowfish
 * Method:    blowfish_encrypt
 * Signature: (Ljava/nio/ByteBuffer;jj)[[B
 */
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeBlowfish_blowfish_1encrypt
        (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     org_bitcoin_NativeBlowfish
 * Method:    blowfish_encrypt
 * Signature: (Ljava/nio/ByteBuffer;jj)[[B
 */
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeBlowfish_blowfish_1decrypt
        (JNIEnv *, jclass, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
